//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 21:14:56 2024 by ROOT version 6.26/07)
//      from the StreamerInfo in file /exp/dune/data/users/noeroy/mywork/MiniRun5/edepsim/MiniRun5_1E19_RHC.spill.0000000.EDEPSIM_SPILLS.root
//////////////////////////////////////////////////////////


#ifndef TG4HitSegment_h
#define TG4HitSegment_h
class TG4HitSegment;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TLorentzVector.h"

class TG4HitSegment : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector< int> Contrib;     //
   int         PrimaryId;    //
   float       EnergyDeposit;    //
   float       SecondaryDeposit;    //
   float       TrackLength;         //
   TLorentzVector Start;               //
   TLorentzVector Stop;                //

   TG4HitSegment();
   TG4HitSegment(TG4HitSegment && ) = default;
   TG4HitSegment &operator=(const TG4HitSegment & );
   TG4HitSegment(const TG4HitSegment & );
   virtual ~TG4HitSegment();

   ClassDef(TG4HitSegment,4); // Generated by MakeProject.
};
#endif
