//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 21:14:56 2024 by ROOT version 6.26/07)
//      from the StreamerInfo in file /exp/dune/data/users/noeroy/mywork/MiniRun5/edepsim/MiniRun5_1E19_RHC.spill.0000000.EDEPSIM_SPILLS.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryParticle_h
#define TG4PrimaryParticle_h
class TG4PrimaryParticle;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"

class TG4PrimaryParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         TrackId;     //
   std::string      Name;        //
   int         PDGCode;     //
   TLorentzVector Momentum;    //

   TG4PrimaryParticle();
   TG4PrimaryParticle(TG4PrimaryParticle && ) = default;
   TG4PrimaryParticle &operator=(const TG4PrimaryParticle & );
   TG4PrimaryParticle(const TG4PrimaryParticle & );
   virtual ~TG4PrimaryParticle();

   ClassDef(TG4PrimaryParticle,4); // Generated by MakeProject.
};
#endif
