//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 21:14:56 2024 by ROOT version 6.26/07)
//      from the StreamerInfo in file /exp/dune/data/users/noeroy/mywork/MiniRun5/edepsim/MiniRun5_1E19_RHC.spill.0000000.EDEPSIM_SPILLS.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryVertex_h
#define TG4PrimaryVertex_h
class TG4PrimaryVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4PrimaryParticle.h"
#include "TG4PrimaryVertex.h"
#include "TLorentzVector.h"
#include <string>

class TG4PrimaryVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector< TG4PrimaryParticle> Particles;    //
   std::vector< TG4PrimaryVertex>   Informational;    //
   TLorentzVector             Position;         //
   std::string                     GeneratorName;    //
   std::string                     Reaction;         //
   std::string                     Filename;         //
   int                        InteractionNumber;    //
   float                      CrossSection;         //
   float                      DiffCrossSection;     //
   float                      Weight;               //
   float                      Probability;          //

   TG4PrimaryVertex();
   TG4PrimaryVertex(TG4PrimaryVertex && ) = default;
   TG4PrimaryVertex &operator=(const TG4PrimaryVertex & );
   TG4PrimaryVertex(const TG4PrimaryVertex & );
   virtual ~TG4PrimaryVertex();

   ClassDef(TG4PrimaryVertex,5); // Generated by MakeProject.
};
#endif
