//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 21:14:56 2024 by ROOT version 6.26/07)
//      from the StreamerInfo in file /exp/dune/data/users/noeroy/mywork/MiniRun5/edepsim/MiniRun5_1E19_RHC.spill.0000000.EDEPSIM_SPILLS.root
//////////////////////////////////////////////////////////


#ifndef TG4Trajectory_h
#define TG4Trajectory_h
class TG4Trajectory;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4TrajectoryPoint.h"
#include <string>
#include "TLorentzVector.h"

class TG4Trajectory : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector< TG4TrajectoryPoint> Points;      //
   int                        TrackId;     //
   int                        ParentId;    //
   std::string                     Name;        //
   int                        PDGCode;     //
   TLorentzVector             InitialMomentum;    //

   TG4Trajectory();
   TG4Trajectory(TG4Trajectory && ) = default;
   TG4Trajectory &operator=(const TG4Trajectory & );
   TG4Trajectory(const TG4Trajectory & );
   virtual ~TG4Trajectory();

   ClassDef(TG4Trajectory,4); // Generated by MakeProject.
};
#endif
