//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Jul 18 21:14:56 2024 by ROOT version 6.26/07)
//      from the StreamerInfo in file /exp/dune/data/users/noeroy/mywork/MiniRun5/edepsim/MiniRun5_1E19_RHC.spill.0000000.EDEPSIM_SPILLS.root
//////////////////////////////////////////////////////////


#ifndef TG4TrajectoryPoint_h
#define TG4TrajectoryPoint_h
class TG4TrajectoryPoint;

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

class TG4TrajectoryPoint : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   TVector3       Momentum;    //
   int            Process;     //
   int            Subprocess;    //

   TG4TrajectoryPoint();
   TG4TrajectoryPoint(TG4TrajectoryPoint && ) = default;
   TG4TrajectoryPoint &operator=(const TG4TrajectoryPoint & );
   TG4TrajectoryPoint(const TG4TrajectoryPoint & );
   virtual ~TG4TrajectoryPoint();

   ClassDef(TG4TrajectoryPoint,4); // Generated by MakeProject.
};
#endif
