
//  WARNING:
//    This file was autogenerated by h5_to_cpp.py.
//    Do not edit by hand!
//    
//    The invocation that generated this file was:
//
//       ND_CAFMaker/scripts/h5_to_cpp.py -f /pscratch/sd/d/dunepro/mkramer/output/Reflow_2x2_v12/run-mlreco/Reflow_2x2_v12.spine/MLRECO_SPINE/beam/july8_2024/nominal_hv/Reflow_2x2_v12.spine.packet-0050017-2024_07_09_00_14_34_CDT.MLRECO_SPINE.hdf5 -o DLP_h5_classes -ns cafmaker::types::dlp -d events -cn Event -d reco_interactions -cn Interaction -d reco_particles -cn Particle -d truth_interactions -cn TrueInteraction -d truth_particles -cn TrueParticle -d flashes -cn Flash -d run_info -cn RunInfo -d trigger -cn Trigger
//


#ifndef CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H
#define CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H

#include <array>

#include "H5Cpp.h"
#include "readH5/BufferView.h"

namespace cafmaker::types::dlp
{

  // This generic template will be overloaded
  // for every specific type that we create below
  template <typename T>
  H5::CompType BuildCompType();

  
  enum class Chi2Pid : int64_t
  {
    kELECTRON = 1,
    kKAON = 5,
    kMUON = 2,
    kPHOTON = 0,
    kPION = 3,
    kPROTON = 4,
    kUNKNOWN = -1,
  };
  
  
  enum class Shape : int64_t
  {
    kDELTA = 3,
    kGHOST = 5,
    kLARCV_UNKNOWN = 6,
    kLOWE = 4,
    kMICHEL = 2,
    kSHOWER = 0,
    kTRACK = 1,
    kUNKNOWN = -1,
  };
  
  
  enum class Pid : int64_t
  {
    kELECTRON = 1,
    kKAON = 5,
    kMUON = 2,
    kPHOTON = 0,
    kPION = 3,
    kPROTON = 4,
    kUNKNOWN = -1,
  };
  
  
  enum class CurrentType : int64_t
  {
    kCC = 0,
    kNC = 1,
    kUNKNOWN = -1,
  };
  
  
  enum class InteractionScheme : int64_t
  {
    kGENIE = 1,
    kGIBUU = 2,
    kLARSOFT = 0,
    kNEUT = 4,
    kNUWRO = 3,
    kUNKNOWN = -1,
  };
  
  struct Event;
  struct Interaction;
  struct Particle;
  struct TrueInteraction;
  struct TrueParticle;
  struct Flash;
  struct RunInfo;
  struct Trigger;
  
  struct Event
  {
    hdset_reg_ref_t index;
    hdset_reg_ref_t reco_interactions;
    hdset_reg_ref_t flashes;
    hdset_reg_ref_t source_file_index;
    hdset_reg_ref_t run_info;
    hdset_reg_ref_t reco_particles;
    hdset_reg_ref_t depositions;
    hdset_reg_ref_t points;
    hdset_reg_ref_t source_file_entry_index;
    hdset_reg_ref_t meta;
    hdset_reg_ref_t truth_interactions;
    hdset_reg_ref_t truth_particles;
    hdset_reg_ref_t trigger;
    
    void SyncVectors();
    
    template <typename T>
    const hdset_reg_ref_t& GetRef() const
    {
      if constexpr(std::is_same_v<T, Interaction>) return reco_interactions;
      else if(std::is_same_v<T, Flash>) return flashes;
      else if(std::is_same_v<T, RunInfo>) return run_info;
      else if(std::is_same_v<T, Particle>) return reco_particles;
      else if(std::is_same_v<T, TrueInteraction>) return truth_interactions;
      else if(std::is_same_v<T, TrueParticle>) return truth_particles;
      else if(std::is_same_v<T, Trigger>) return trigger;
    }
    
  };
  
  
  struct Interaction
  {
    bool is_truth;
    char * units;
    int64_t id;
    bool is_contained;
    bool is_time_contained;
    bool is_cathode_crosser;
    bool is_matched;
    double cathode_offset;
    BufferView<int32_t> index;
    BufferView<int32_t> orig_index;
    BufferView<int32_t> match_ids;
    BufferView<float> match_overlaps;
    bool is_fiducial;
    bool is_flash_matched;
    double flash_total_pe;
    double flash_hypo_pe;
    BufferView<int32_t> particle_ids;
    std::array<float, 3> vertex;
    BufferView<int32_t> flash_ids;
    BufferView<int32_t> flash_volume_ids;
    BufferView<float> flash_times;
    BufferView<float> flash_scores;
    BufferView<int32_t> flash_hypothesis_ids;
    std::array<float, 3> dir;
    BufferView<int32_t> primary_particle_ids;
    int64_t num_particles;
    int64_t num_primary_particles;
    std::array<int32_t, 6> particle_counts;
    std::array<int32_t, 6> primary_particle_counts;
    bool is_crt_matched;
    BufferView<int32_t> crt_ids;
    BufferView<float> crt_times;
    BufferView<float> crt_scores;
    char * topology;
    int64_t size;
    double depositions_sum;
    double depositions_q_sum;
    int64_t best_match_id;
    double best_match_overlap;
    BufferView<int32_t> module_ids;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t index_handle;
    hvl_t orig_index_handle;
    hvl_t match_ids_handle;
    hvl_t match_overlaps_handle;
    hvl_t particle_ids_handle;
    hvl_t flash_ids_handle;
    hvl_t flash_volume_ids_handle;
    hvl_t flash_times_handle;
    hvl_t flash_scores_handle;
    hvl_t flash_hypothesis_ids_handle;
    hvl_t primary_particle_ids_handle;
    hvl_t crt_ids_handle;
    hvl_t crt_times_handle;
    hvl_t crt_scores_handle;
    hvl_t module_ids_handle;
  };
  
  
  struct Particle
  {
    bool is_truth;
    char * units;
    int64_t id;
    bool is_contained;
    bool is_time_contained;
    bool is_cathode_crosser;
    bool is_matched;
    double cathode_offset;
    BufferView<int32_t> index;
    BufferView<int32_t> orig_index;
    BufferView<int32_t> match_ids;
    BufferView<float> match_overlaps;
    int64_t interaction_id;
    Chi2Pid chi2_pid;
    bool is_primary;
    bool is_crt_matched;
    bool is_valid;
    double length;
    double calo_ke;
    double csda_ke;
    double mcs_ke;
    Shape shape;
    Pid pid;
    BufferView<int32_t> fragment_ids;
    std::array<float, 3> start_point;
    std::array<float, 3> end_point;
    std::array<float, 6> chi2_per_pid;
    std::array<float, 6> csda_ke_per_pid;
    std::array<float, 6> mcs_ke_per_pid;
    BufferView<int32_t> crt_ids;
    BufferView<float> crt_times;
    BufferView<float> crt_scores;
    double start_dedx;
    double end_dedx;
    double vertex_distance;
    double start_straightness;
    double directional_spread;
    double axial_spread;
    std::array<float, 3> start_dir;
    std::array<float, 3> end_dir;
    std::array<float, 6> pid_scores;
    std::array<float, 2> primary_scores;
    BufferView<int32_t> ppn_ids;
    int64_t pdg_code;
    double mass;
    double ke;
    std::array<float, 3> momentum;
    double p;
    int64_t num_fragments;
    int64_t size;
    double depositions_sum;
    double depositions_q_sum;
    int64_t best_match_id;
    double best_match_overlap;
    BufferView<int32_t> module_ids;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t index_handle;
    hvl_t orig_index_handle;
    hvl_t match_ids_handle;
    hvl_t match_overlaps_handle;
    hvl_t fragment_ids_handle;
    hvl_t crt_ids_handle;
    hvl_t crt_times_handle;
    hvl_t crt_scores_handle;
    hvl_t ppn_ids_handle;
    hvl_t module_ids_handle;
  };
  
  
  struct TrueInteraction
  {
    int64_t orig_id;
    bool is_truth;
    BufferView<int32_t> index_adapt;
    BufferView<int32_t> index_g4;
    char * units;
    int64_t id;
    bool is_contained;
    bool is_time_contained;
    bool is_cathode_crosser;
    bool is_matched;
    double cathode_offset;
    BufferView<int32_t> index;
    BufferView<int32_t> orig_index;
    BufferView<int32_t> match_ids;
    BufferView<float> match_overlaps;
    bool is_fiducial;
    bool is_flash_matched;
    double flash_total_pe;
    double flash_hypo_pe;
    BufferView<int32_t> particle_ids;
    std::array<float, 3> vertex;
    BufferView<int32_t> flash_ids;
    BufferView<int32_t> flash_volume_ids;
    BufferView<float> flash_times;
    BufferView<float> flash_scores;
    BufferView<int32_t> flash_hypothesis_ids;
    int64_t interaction_id;
    CurrentType current_type;
    InteractionScheme interaction_scheme;
    int64_t interaction_mode;
    int64_t interaction_type;
    int64_t mct_index;
    int64_t track_id;
    int64_t lepton_track_id;
    int64_t pdg_code;
    int64_t lepton_pdg_code;
    int64_t target;
    int64_t nucleon;
    int64_t quark;
    double energy_init;
    double hadronic_invariant_mass;
    double momentum_transfer;
    double momentum_transfer_mag;
    double energy_transfer;
    double lepton_p;
    double distance_travel;
    double t;
    double theta;
    double bjorken_x;
    double inelasticity;
    char * creation_process;
    std::array<float, 3> position;
    std::array<float, 3> momentum;
    int64_t nu_id;
    std::array<float, 3> reco_vertex;
    std::array<float, 3> reco_dir;
    double time;
    std::array<float, 3> dir;
    BufferView<int32_t> primary_particle_ids;
    int64_t num_particles;
    int64_t num_primary_particles;
    std::array<int32_t, 6> particle_counts;
    std::array<int32_t, 6> primary_particle_counts;
    bool is_crt_matched;
    BufferView<int32_t> crt_ids;
    BufferView<float> crt_times;
    BufferView<float> crt_scores;
    char * topology;
    int64_t size;
    double depositions_sum;
    double depositions_q_sum;
    int64_t best_match_id;
    double best_match_overlap;
    BufferView<int32_t> module_ids;
    int64_t size_adapt;
    int64_t size_g4;
    double depositions_adapt_sum;
    double depositions_adapt_q_sum;
    double depositions_g4_sum;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t index_adapt_handle;
    hvl_t index_g4_handle;
    hvl_t index_handle;
    hvl_t orig_index_handle;
    hvl_t match_ids_handle;
    hvl_t match_overlaps_handle;
    hvl_t particle_ids_handle;
    hvl_t flash_ids_handle;
    hvl_t flash_volume_ids_handle;
    hvl_t flash_times_handle;
    hvl_t flash_scores_handle;
    hvl_t flash_hypothesis_ids_handle;
    hvl_t primary_particle_ids_handle;
    hvl_t crt_ids_handle;
    hvl_t crt_times_handle;
    hvl_t crt_scores_handle;
    hvl_t module_ids_handle;
  };
  
  
  struct TrueParticle
  {
    int64_t orig_id;
    bool is_truth;
    BufferView<int32_t> index_adapt;
    BufferView<int32_t> index_g4;
    char * units;
    int64_t id;
    bool is_contained;
    bool is_time_contained;
    bool is_cathode_crosser;
    bool is_matched;
    double cathode_offset;
    BufferView<int32_t> index;
    BufferView<int32_t> orig_index;
    BufferView<int32_t> match_ids;
    BufferView<float> match_overlaps;
    int64_t interaction_id;
    Chi2Pid chi2_pid;
    bool is_primary;
    bool is_crt_matched;
    bool is_valid;
    double length;
    double calo_ke;
    double csda_ke;
    double mcs_ke;
    Shape shape;
    Pid pid;
    BufferView<int32_t> fragment_ids;
    std::array<float, 3> start_point;
    std::array<float, 3> end_point;
    std::array<float, 6> chi2_per_pid;
    std::array<float, 6> csda_ke_per_pid;
    std::array<float, 6> mcs_ke_per_pid;
    BufferView<int32_t> crt_ids;
    BufferView<float> crt_times;
    BufferView<float> crt_scores;
    int64_t parent_id;
    int64_t group_id;
    int64_t nu_id;
    BufferView<int32_t> children_id;
    int64_t mct_index;
    int64_t mcst_index;
    int64_t group_primary;
    int64_t interaction_primary;
    int64_t track_id;
    int64_t parent_track_id;
    int64_t ancestor_track_id;
    int64_t pdg_code;
    int64_t parent_pdg_code;
    int64_t ancestor_pdg_code;
    int64_t num_voxels;
    double t;
    double end_t;
    double first_step_t;
    double last_step_t;
    double parent_t;
    double ancestor_t;
    double energy_init;
    double energy_deposit;
    double distance_travel;
    char * creation_process;
    char * parent_creation_process;
    char * ancestor_creation_process;
    std::array<float, 3> position;
    std::array<float, 3> end_position;
    std::array<float, 3> parent_position;
    std::array<float, 3> ancestor_position;
    std::array<float, 3> first_step;
    std::array<float, 3> last_step;
    std::array<float, 3> momentum;
    std::array<float, 3> end_momentum;
    int64_t orig_interaction_id;
    int64_t orig_parent_id;
    int64_t orig_group_id;
    double reco_length;
    BufferView<int32_t> orig_children_id;
    BufferView<int32_t> children_counts;
    std::array<float, 3> reco_start_dir;
    std::array<float, 3> reco_end_dir;
    std::array<float, 3> start_dir;
    std::array<float, 3> end_dir;
    double ke;
    double reco_ke;
    std::array<float, 3> reco_momentum;
    double p;
    double end_p;
    double mass;
    int64_t num_fragments;
    int64_t size;
    double depositions_sum;
    double depositions_q_sum;
    int64_t best_match_id;
    double best_match_overlap;
    BufferView<int32_t> module_ids;
    int64_t size_adapt;
    int64_t size_g4;
    double depositions_adapt_sum;
    double depositions_adapt_q_sum;
    double depositions_g4_sum;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t index_adapt_handle;
    hvl_t index_g4_handle;
    hvl_t index_handle;
    hvl_t orig_index_handle;
    hvl_t match_ids_handle;
    hvl_t match_overlaps_handle;
    hvl_t fragment_ids_handle;
    hvl_t crt_ids_handle;
    hvl_t crt_times_handle;
    hvl_t crt_scores_handle;
    hvl_t children_id_handle;
    hvl_t orig_children_id_handle;
    hvl_t children_counts_handle;
    hvl_t module_ids_handle;
  };
  
  
  struct Flash
  {
    char * units;
    int64_t id;
    int64_t volume_id;
    int64_t frame;
    int64_t on_beam_time;
    bool in_beam_frame;
    double time;
    double time_width;
    double time_abs;
    double total_pe;
    double fast_to_total;
    BufferView<float> pe_per_ch;
    std::array<float, 3> center;
    std::array<float, 3> width;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t pe_per_ch_handle;
  };
  
  
  struct RunInfo
  {
    int64_t run;
    int64_t subrun;
    int64_t event;
    
    void SyncVectors();
  };
  
  
  struct Trigger
  {
    int64_t id;
    int64_t type;
    int64_t time_s;
    int64_t time_ns;
    int64_t beam_time_s;
    int64_t beam_time_ns;
    
    void SyncVectors();
  };
  
  
  template <>
  H5::CompType BuildCompType<Event>();
  
  
  template <>
  H5::CompType BuildCompType<Interaction>();
  
  
  template <>
  H5::CompType BuildCompType<Particle>();
  
  
  template <>
  H5::CompType BuildCompType<TrueInteraction>();
  
  
  template <>
  H5::CompType BuildCompType<TrueParticle>();
  
  
  template <>
  H5::CompType BuildCompType<Flash>();
  
  
  template <>
  H5::CompType BuildCompType<RunInfo>();
  
  
  template <>
  H5::CompType BuildCompType<Trigger>();
  

}

#endif // CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H
