
//  WARNING:
//    This file was autogenerated by h5_to_cpp.py.
//    Do not edit by hand!

#ifndef CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H
#define CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H

#include <array>

#include "H5Cpp.h"
#include "readH5/BufferView.h"

namespace cafmaker::types::dlp
{

  // This generic template will be overloaded
  // for every specific type that we create below
  template <typename T>
  H5::CompType BuildCompType();

  
  enum Pid_t : int64_t
  {
    kElectron = 1,
    kMuon = 2,
    kPhoton = 0,
    kPion = 3,
    kProton = 4,
  };
  
  
  enum SemanticType_t : int64_t
  {
    kDelta = 3,
    kGhost = 5,
    kLowEnergy = 4,
    kMichel = 2,
    kShower = 0,
    kTrack = 1,
    kUnknown = 6,
  };
  
  struct Event;
  struct Particle;
  struct Interaction;
  struct TrueInteraction;
  struct TrueParticle;
  
  struct Event
  {
    hdset_reg_ref_t meta;
    hdset_reg_ref_t index;
    hdset_reg_ref_t truth_interactions;
    hdset_reg_ref_t truth_particles;
    hdset_reg_ref_t particles;
    hdset_reg_ref_t interactions;
    
    void SyncVectors();
    
    template <typename T>
    const hdset_reg_ref_t& GetRef() const
    {
      if constexpr(std::is_same_v<T, TrueInteraction>) return truth_interactions;
      else if(std::is_same_v<T, TrueParticle>) return truth_particles;
      else if(std::is_same_v<T, Particle>) return particles;
      else if(std::is_same_v<T, Interaction>) return interactions;
    }
    
  };
  
  
  struct Particle
  {
    double depositions_sum;
    std::array<float, 3> end_dir;
    std::array<double, 3> end_point;
    BufferView<int64_t> fragment_ids;
    int64_t id;
    int64_t image_id;
    BufferView<int64_t> index;
    int64_t interaction_id;
    bool is_primary;
    BufferView<int64_t> match;
    BufferView<float> match_counts;
    double momentum_mcs;
    double momentum_range;
    int64_t nu_id;
    int64_t num_fragments;
    Pid_t pid;
    std::array<float, 5> pid_scores;
    std::array<float, 2> primary_scores;
    SemanticType_t semantic_type;
    int64_t size;
    std::array<float, 3> start_dir;
    std::array<double, 3> start_point;
    int64_t volume_id;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t fragment_ids_handle;
    hvl_t index_handle;
    hvl_t match_handle;
    hvl_t match_counts_handle;
  };
  
  
  struct Interaction
  {
    int64_t flash_hypothesis;
    int64_t flash_id;
    double flash_time;
    int64_t flash_total_pE;
    uint8_t fmatched;
    int64_t id;
    int64_t image_id;
    bool is_neutrino;
    BufferView<int64_t> match;
    BufferView<float> match_counts;
    int64_t nu_id;
    int64_t num_particles;
    int64_t num_primaries;
    std::array<int64_t, 6> particle_counts;
    BufferView<int64_t> particle_ids;
    std::array<int64_t, 6> primary_counts;
    int64_t size;
    std::array<double, 3> vertex;
    int64_t volume_id;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t match_handle;
    hvl_t match_counts_handle;
    hvl_t particle_ids_handle;
  };
  
  
  struct TrueInteraction
  {
    int64_t flash_hypothesis;
    int64_t flash_id;
    double flash_time;
    int64_t flash_total_pE;
    uint8_t fmatched;
    int64_t id;
    int64_t image_id;
    bool is_neutrino;
    BufferView<int64_t> match;
    BufferView<float> match_counts;
    int64_t nu_current_type;
    double nu_energy_init;
    int64_t nu_id;
    int64_t nu_interaction_mode;
    int64_t nu_interaction_type;
    int64_t num_particles;
    int64_t num_primaries;
    std::array<int64_t, 6> particle_counts;
    BufferView<int64_t> particle_ids;
    std::array<int64_t, 6> primary_counts;
    int64_t size;
    std::array<double, 3> vertex;
    int64_t volume_id;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t match_handle;
    hvl_t match_counts_handle;
    hvl_t particle_ids_handle;
  };
  
  
  struct TrueParticle
  {
    double depositions_sum;
    std::array<float, 3> end_dir;
    std::array<float, 3> end_point;
    std::array<float, 4> end_position;
    BufferView<int64_t> fragment_ids;
    int64_t id;
    int64_t image_id;
    BufferView<int64_t> index;
    int64_t interaction_id;
    bool is_primary;
    BufferView<int64_t> match;
    BufferView<float> match_counts;
    std::array<float, 3> momentum;
    double momentum_mcs;
    double momentum_range;
    int64_t nu_id;
    int64_t num_fragments;
    Pid_t pid;
    std::array<float, 5> pid_scores;
    std::array<float, 2> primary_scores;
    SemanticType_t semantic_type;
    int64_t size;
    std::array<float, 3> start_dir;
    std::array<float, 3> start_point;
    std::array<float, 4> start_position;
    BufferView<int64_t> truth_index;
    int64_t truth_size;
    int64_t volume_id;
    
    void SyncVectors();
    
    // note: the following 'handle' objects
    // are used internally by HDF5 to keep track
    // of the memory for variable-length buffers.
    // please use the SyncVectors() method
    // after loading data into the object
    // to fill the corresponding BufferView<>s above,
    // and then use those for access to the data.
    
    hvl_t fragment_ids_handle;
    hvl_t index_handle;
    hvl_t match_handle;
    hvl_t match_counts_handle;
    hvl_t truth_index_handle;
  };
  
  
  template <>
  H5::CompType BuildCompType<Event>();
  
  
  template <>
  H5::CompType BuildCompType<Particle>();
  
  
  template <>
  H5::CompType BuildCompType<Interaction>();
  
  
  template <>
  H5::CompType BuildCompType<TrueInteraction>();
  
  
  template <>
  H5::CompType BuildCompType<TrueParticle>();
  

}

#endif // CAFMAKER_TYPES_DLP_DLP_H5_CLASSES_H
