# Disable edep-sim's trajectory pruning.  This usually does us more harm than good.
# NOTE that one must NOT pass '-u' to edep-sim when invoking this macro
# or you'll get errors.  (the /edep/update command below *replaces* the '-u'.)
/edep/db/set/neutronThreshold 0 MeV
/edep/db/set/lengthThreshold 0 mm
/edep/db/set/gammaThreshold 0 MeV
/edep/update

/generator/kinematics/set rooTracker
/generator/kinematics/rooTracker/input input_file.gtrac.root
/generator/position/set free
/generator/time/set fixed
/generator/count/fixed/number 1
/generator/count/set fixed
/generator/add
